# Generated by Django 3.2.14 on 2022-07-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='submitter',
            field=models.TextField(null=True),
        ),
    ]
